BEGIN;

UPDATE model_catalog_models
SET
  meta = CASE model_key
    WHEN 'gemini-3.1-flash-image-preview' THEN '{"imageOptions":{"defaultAspectRatio":"1:1","defaultImageSize":"2K","aspectRatioOptions":["1:1","16:9","9:16","4:3","3:4"],"imageSizeOptions":[{"value":"1K","label":"1K"},{"value":"2K","label":"2K"},{"value":"4K","label":"4K"}],"resolutionOptions":[{"value":"1K","label":"1K 输出"},{"value":"2K","label":"2K 输出"},{"value":"4K","label":"4K 输出"}],"controls":[{"key":"aspect_ratio","binding":"aspectRatio","label":"比例"},{"key":"image_size","binding":"imageSize","label":"尺寸"},{"key":"resolution","binding":"resolution","label":"分辨率"}],"supportsReferenceImages":true,"supportsTextToImage":true,"supportsImageToImage":true},"useCases":["image_generation","image_edit","vision","reference_guided"]}'
    WHEN 'nano-banana' THEN '{"imageOptions":{"defaultAspectRatio":"1:1","defaultImageSize":"2K","aspectRatioOptions":["1:1","16:9","9:16","4:3","3:4","3:2","2:3"],"imageSizeOptions":[{"value":"1K","label":"1K"},{"value":"2K","label":"2K"},{"value":"4K","label":"4K"}],"resolutionOptions":[{"value":"1K","label":"1K 输出"},{"value":"2K","label":"2K 输出"},{"value":"4K","label":"4K 输出"}],"controls":[{"key":"aspect_ratio","binding":"aspectRatio","label":"比例"},{"key":"image_size","binding":"imageSize","label":"尺寸"},{"key":"resolution","binding":"resolution","label":"分辨率"}],"supportsReferenceImages":true,"supportsTextToImage":true,"supportsImageToImage":true},"useCases":["image_generation","storyboard_still","character_consistency","reference_guided"]}'
    WHEN 'nano-banana-fast' THEN '{"imageOptions":{"defaultAspectRatio":"1:1","defaultImageSize":"1K","aspectRatioOptions":["1:1","16:9","9:16","4:3","3:4"],"imageSizeOptions":[{"value":"1K","label":"1K"},{"value":"2K","label":"2K"}],"resolutionOptions":[{"value":"1K","label":"1K 输出"},{"value":"2K","label":"2K 输出"}],"controls":[{"key":"aspect_ratio","binding":"aspectRatio","label":"比例"},{"key":"image_size","binding":"imageSize","label":"尺寸"},{"key":"resolution","binding":"resolution","label":"分辨率"}],"supportsReferenceImages":true,"supportsTextToImage":true,"supportsImageToImage":true},"useCases":["image_generation","fast_iteration","reference_guided"]}'
    WHEN 'nano-banana-pro' THEN '{"imageOptions":{"defaultAspectRatio":"1:1","defaultImageSize":"2K","aspectRatioOptions":["1:1","16:9","9:16","4:3","3:4","3:2","2:3","21:9"],"imageSizeOptions":[{"value":"1K","label":"1K"},{"value":"2K","label":"2K"},{"value":"4K","label":"4K"}],"resolutionOptions":[{"value":"1K","label":"1K 输出"},{"value":"2K","label":"2K 输出"},{"value":"4K","label":"4K 输出"}],"controls":[{"key":"aspect_ratio","binding":"aspectRatio","label":"比例"},{"key":"image_size","binding":"imageSize","label":"尺寸"},{"key":"resolution","binding":"resolution","label":"分辨率"}],"supportsReferenceImages":true,"supportsTextToImage":true,"supportsImageToImage":true},"useCases":["image_generation","storyboard_still","character_consistency","high_quality","reference_guided"]}'
    WHEN 'gemini-2.5-flash-image' THEN '{"imageOptions":{"defaultAspectRatio":"1:1","defaultImageSize":"1K","aspectRatioOptions":["1:1","16:9","9:16","4:3","3:4"],"imageSizeOptions":[{"value":"1K","label":"1K"},{"value":"2K","label":"2K"}],"resolutionOptions":[{"value":"1K","label":"1K 输出"},{"value":"2K","label":"2K 输出"}],"controls":[{"key":"aspect_ratio","binding":"aspectRatio","label":"比例"},{"key":"image_size","binding":"imageSize","label":"尺寸"},{"key":"resolution","binding":"resolution","label":"分辨率"}],"supportsReferenceImages":true,"supportsTextToImage":true,"supportsImageToImage":true},"useCases":["image_generation","vision","fast_iteration"]}'
    WHEN 'qwen-image-plus' THEN '{"imageOptions":{"defaultAspectRatio":"1:1","defaultImageSize":"2K","aspectRatioOptions":["1:1","16:9","9:16","4:3","3:4"],"imageSizeOptions":[{"value":"1K","label":"1K"},{"value":"2K","label":"2K"},{"value":"4K","label":"4K"}],"resolutionOptions":[{"value":"1K","label":"1K 输出"},{"value":"2K","label":"2K 输出"},{"value":"4K","label":"4K 输出"}],"controls":[{"key":"aspect_ratio","binding":"aspectRatio","label":"比例"},{"key":"image_size","binding":"imageSize","label":"尺寸"},{"key":"resolution","binding":"resolution","label":"分辨率"}],"supportsReferenceImages":true,"supportsTextToImage":true,"supportsImageToImage":true},"useCases":["image_generation","strict_size","reference_guided"]}'
    WHEN 'veo3.1-pro' THEN '{"videoOptions":{"defaultDurationSeconds":5,"defaultResolution":"1080p","durationOptions":[{"value":5,"label":"5s"},{"value":8,"label":"8s"}],"resolutionOptions":[{"value":"720p","label":"720p"},{"value":"1080p","label":"1080p"}],"orientationOptions":[{"value":"landscape","label":"横屏","aspectRatio":"16:9"},{"value":"portrait","label":"竖屏","aspectRatio":"9:16"}],"controls":[{"key":"duration","binding":"durationSeconds","label":"时长"},{"key":"resolution","binding":"resolution","label":"分辨率"},{"key":"orientation","binding":"orientation","label":"方向"}]},"useCases":["text_to_video","image_to_video","cinematic","high_quality"]}'
    WHEN 'veo3.1-fast' THEN '{"videoOptions":{"defaultDurationSeconds":5,"defaultResolution":"720p","durationOptions":[{"value":5,"label":"5s"},{"value":8,"label":"8s"}],"resolutionOptions":[{"value":"720p","label":"720p"},{"value":"1080p","label":"1080p"}],"orientationOptions":[{"value":"landscape","label":"横屏","aspectRatio":"16:9"},{"value":"portrait","label":"竖屏","aspectRatio":"9:16"}],"controls":[{"key":"duration","binding":"durationSeconds","label":"时长"},{"key":"resolution","binding":"resolution","label":"分辨率"},{"key":"orientation","binding":"orientation","label":"方向"}]},"useCases":["text_to_video","image_to_video","fast_iteration"]}'
    WHEN 'veo_3_1_i2v_s_fast_fl_landscape' THEN '{"videoOptions":{"defaultDurationSeconds":5,"defaultResolution":"720p","defaultOrientation":"landscape","durationOptions":[{"value":5,"label":"5s"},{"value":8,"label":"8s"}],"resolutionOptions":[{"value":"720p","label":"720p"},{"value":"1080p","label":"1080p"}],"orientationOptions":[{"value":"landscape","label":"横屏","aspectRatio":"16:9"}],"controls":[{"key":"duration","binding":"durationSeconds","label":"时长"},{"key":"resolution","binding":"resolution","label":"分辨率"}]},"useCases":["image_to_video","first_last_frame","landscape_only"]}'
    ELSE meta
  END,
  updated_at = '2026-04-15T00:00:00.000Z'
WHERE model_key IN (
  'gemini-3.1-flash-image-preview',
  'nano-banana',
  'nano-banana-fast',
  'nano-banana-pro',
  'gemini-2.5-flash-image',
  'qwen-image-plus',
  'veo3.1-pro',
  'veo3.1-fast',
  'veo_3_1_i2v_s_fast_fl_landscape'
);

COMMIT;
